In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 108.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 145.2 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 203.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 5.5 MB/s eta 0:00:03
    --------------------------------------- 0.2/15.5 MB 3.0 MB/s eta 0:00:06
    --------------------------------------- 0.4/15.5 MB 3.3 MB/s eta 0:00:05
   - -------------------------------------- 0.5/15.5 MB 3.1 MB/s eta 0:00:05
   -

In [7]:
import numpy as np

In [9]:
a=np.arange(6)
a2=a[np.newaxis, :]
a2.shape

(1, 6)

In [10]:
a = np.array([1,2,3,4,5,6])

In [12]:
a

array([1, 2, 3, 4, 5, 6])

In [14]:
a = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
print(a[0])

[1 2 3 4]


In [21]:
import numpy as np

In [25]:
a=np.array([1,2,3])

In [26]:
a

array([1, 2, 3])

In [30]:
np.zeros(2)

array([0., 0.])

In [31]:
np.ones(2)

array([1., 1.])

In [34]:
np.empty(2)

array([1., 1.])

In [35]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [36]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
x=np.ones(2, dtype=np.int64)

In [38]:
x

array([1, 1], dtype=int64)

In [39]:
arr=np.array([2,1,5,3,7,4,6,8])

In [40]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
a=np.array([1,2,3,4])

In [42]:
b=np.array([5,6,7,8])

In [45]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

In [61]:
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
array_example = np.array([[[0,1,2,3], [4,5,6,7]], [[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])

In [64]:
array_example.ndim

3

In [66]:
array_example.size

24

In [68]:
array_example.shape

(3, 2, 4)

In [70]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [71]:
b= a.reshape(3,2)

In [72]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [73]:
np.reshape(a, newshape=(1,6), order='c')

array([[0, 1, 2, 3, 4, 5]])

In [74]:
a=np.array([1,2,3,4,5,6])

In [75]:
a.shape

(6,)

In [76]:
a2=a[np.newaxis, :]

In [77]:
a2.shape

(1, 6)

In [78]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [80]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [81]:
a=np.array([1,2,3,4,5,6])

In [82]:
a.shape

(6,)

In [83]:
b=np.expand_dims(a,axis=1)

In [84]:
b.shape

(6, 1)

In [85]:
c=np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [87]:
data = np.array([1,2,3])

In [88]:
data[0:2]

array([1, 2])

In [89]:
data[0:2]

array([1, 2])

In [90]:
data[1:]

array([2, 3])

In [91]:
data[-2:]

array([2, 3])

In [92]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [93]:
print(a[a<5])

[1 2 3 4]


In [94]:
five_up = (a >= 5)

In [95]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [96]:
divisible_by_2 = a[a%2==0]

In [97]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [98]:
c= a[(a>2) & (a<11)]

In [99]:
print(c)

[ 3  4  5  6  7  8  9 10]


In [100]:
five_up = (a>5) | (a==5)

In [101]:
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [102]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [103]:
b=np.nonzero(a<5)

In [104]:
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [105]:
list_of_coordinates= list(zip(b[0],b[1]))

In [108]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [109]:
print(a[b])

[1 2 3 4]


In [110]:
not_there = np.nonzero(a==42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [111]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [112]:
arr1 = a[3:8]

In [113]:
arr1

array([4, 5, 6, 7, 8])

In [114]:
a1=np.array([[1,1],[2,2]])

In [115]:
a2=np.array([[3,3],[4,4]])

In [116]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [117]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [118]:
x=np.arange(1,25).reshape(2,12)

In [119]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [120]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [121]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [122]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [123]:
b1=a[0,:]

In [124]:
b1

array([1, 2, 3, 4])

In [125]:
b1[0] =99

In [126]:
b1

array([99,  2,  3,  4])

In [127]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
b2=a.copy()

In [129]:
data = np.array([1,2])

In [130]:
ones = np.ones(2,dtype=int)

In [131]:
data + ones

array([2, 3])

In [132]:
data - ones

array([0, 1])

In [135]:
data * data

array([1, 4])

In [136]:
data / data

array([1., 1.])

In [137]:
a = np.array([1,2,3,4])

In [138]:
a.sum()

10

In [139]:
b=np.array([[1,1],[2,2]])

In [140]:
b.sum(axis=1)

array([2, 4])

In [141]:
data=np.array([1.0,2.0])

In [142]:
data*1.6

array([1.6, 3.2])

In [143]:
data.max()

2.0

In [144]:
data.min()

1.0

In [145]:
data.sum()

3.0

In [146]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [147]:
a.sum()

4.8595784

In [148]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [149]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [150]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [151]:
data[0, 1]

2

In [152]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [153]:
data[0:2, 0]

array([1, 3])

In [154]:
data.max()

6

In [155]:
data.min()

1

In [156]:
data.sum()

21

In [157]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [158]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [159]:
data.max(axis=0)

array([5, 6])

In [160]:
data.max(axis=1)

array([2, 5, 6])

In [161]:
data = np.array([[1,2],[3,4]])

In [162]:
ones = np.array([[1,1],[1,1]])

In [164]:
data+ones

array([[2, 3],
       [4, 5]])

In [165]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [166]:
ones_row = np.array([[1, 1]])

In [167]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [168]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [169]:
np.ones(3)

array([1., 1., 1.])

In [170]:
np.zeros(3)

array([0., 0., 0.])

In [172]:
rng = np.random.default_rng()  # the simplest way to generate random numbers

In [173]:
rng.random(3) 

array([0.88259132, 0.64357999, 0.57476561])

In [174]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [178]:
rng.random((3,2))

array([[0.53149859, 0.48026337],
       [0.63621633, 0.82975526],
       [0.34269616, 0.78144354]])

In [179]:
rng.integers(5, size=(2, 4)) 

array([[4, 0, 4, 3],
       [2, 1, 0, 0]], dtype=int64)

In [180]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [181]:
unique_values = np.unique(a)

In [182]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [183]:
unique_values, indices_list = np.unique(a, return_index=True)

In [184]:
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [185]:
unique_values, occurrence_count = np.unique(a, return_counts=True)

In [186]:
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [187]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [188]:
unique_values = np.unique(a_2d)

In [189]:
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [192]:
unique_rows = np.unique(a_2d, axis=0)

In [193]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [194]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)

In [195]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [196]:
print(indices)

[0 1 2]


In [197]:
print(occurrence_count)

[2 1 1]


In [198]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [199]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [200]:
arr = np.arange(6).reshape((2, 3))

In [201]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [202]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [203]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [204]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [205]:
reversed_arr = np.flip(arr)

In [206]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [207]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [208]:
reversed_arr = np.flip(arr_2d)

In [209]:
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [210]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [211]:
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [212]:
reversed_arr_columns = np.flip(arr_2d, axis=1)

In [213]:
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [214]:
arr_2d[1] = np.flip(arr_2d[1])

In [215]:
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [216]:
arr_2d[:,1] = np.flip(arr_2d[:,1])

In [217]:
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [218]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [219]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [220]:
a1 = x.flatten()

In [221]:
a1[0] = 99

In [222]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [223]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [224]:
a2 = x.ravel()

In [225]:
a2[0]=98

In [226]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [227]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
